import {
  KeymapLayout,
  KeymapGuide,
  KeymapKey,
  KeymapLayer,
} from "@keymapkit/ui";
import { KeyboardModelAdvantage360 } from "@keymapkit/keyboard.advantage360";

export const MrlAdv360 = new KeymapLayout({
  displayName: "My Advantage360 Layout",
  uniqueId: "mrladv360",
  model: KeyboardModelAdvantage360,
  layers: [
    KeymapLayer.fromKeyList({
      displayName: "Main Layer",
      shortName: "Main",
      welcome: [
        `Welcome to my keymap.`,
        `Select a key from the board above to learn more about it.`,
      ],
      keys: [
        // The l-f grid,
        new KeymapKey({ name: "=+", id: "l-f-1-1", info: [""] }),
        new KeymapKey({ name: "1", id: "l-f-6-1", info: [""] }),
        new KeymapKey({ name: "2", id: "l-f-10-1", info: [""] }),
        new KeymapKey({ name: "3", id: "l-f-14-1", info: [""] }),
        new KeymapKey({ name: "4", id: "l-f-18-1", info: [""] }),
        new KeymapKey({ name: "5", id: "l-f-22-1", info: [""] }),
        new KeymapKey({ name: "esc", id: "l-f-26-1", info: [""] }),
        new KeymapKey({ name: "`~", id: "l-f-1-5", info: [""] }),
        new KeymapKey({ name: "q", id: "l-f-6-5", info: [""] }),
        new KeymapKey({ name: "w", id: "l-f-10-5", info: [""] }),
        new KeymapKey({ name: "e", id: "l-f-14-5", info: [""] }),
        new KeymapKey({ name: "r", id: "l-f-18-5", info: [""] }),
        new KeymapKey({ name: "t", id: "l-f-22-5", info: [""] }),
        new KeymapKey({ name: "tab", id: "l-f-26-5", info: [""] }),
        new KeymapKey({ unset: true, name: "", id: "l-f-1-9", info: [""] }),
        new KeymapKey({ name: "a", id: "l-f-6-9", info: [""] }),
        new KeymapKey({ name: "s", id: "l-f-10-9", info: [""] }),
        new KeymapKey({ name: "d", id: "l-f-14-9", info: [""] }),
        new KeymapKey({ name: "f", id: "l-f-18-9", info: [""] }),
        new KeymapKey({ name: "g", id: "l-f-22-9", info: [""] }),
        new KeymapKey({ name: "cmd", id: "l-f-26-9", info: [""] }),
        new KeymapKey({ name: "[{", id: "l-f-1-13", info: [""] }),
        new KeymapKey({ name: "z", id: "l-f-6-13", info: [""] }),
        new KeymapKey({ name: "x", id: "l-f-10-13", info: [""] }),
        new KeymapKey({ name: "c", id: "l-f-14-13", info: [""] }),
        new KeymapKey({ name: "v", id: "l-f-18-13", info: [""] }),
        new KeymapKey({ name: "b", id: "l-f-22-13", info: [""] }),
        new KeymapKey({ name: "Fn F", id: "l-f-1-17", info: [""] }),
        new KeymapKey({ unset: true, name: "", id: "l-f-6-17", info: [""] }),
        new KeymapKey({ unset: true, name: "", id: "l-f-10-17", info: [""] }),
        new KeymapKey({ name: "del", id: "l-f-14-17", info: [""] }),
        new KeymapKey({ name: "opt", id: "l-f-18-17", info: [""] }),
        // The l-t grid,
        new KeymapKey({ name: "FnA", id: "l-t-5-1", info: [""] }),
        new KeymapKey({ name: "FnB", id: "l-t-9-1", info: [""] }),
        new KeymapKey({ name: "shft", id: "l-t-1-5", info: [""] }),
        new KeymapKey({ name: "FnR", id: "l-t-5-5", info: [""] }),
        new KeymapKey({ name: "FnC", id: "l-t-9-5", info: [""] }),
        new KeymapKey({ name: "ctrl", id: "l-t-9-9", info: [""] }),
        // The r-f grid,
        new KeymapKey({ name: "bksp", id: "r-f-1-1", info: [""] }),
        new KeymapKey({ name: "6", id: "r-f-5-1", info: [""] }),
        new KeymapKey({ name: "7", id: "r-f-9-1", info: [""] }),
        new KeymapKey({ name: "8", id: "r-f-13-1", info: [""] }),
        new KeymapKey({ name: "9", id: "r-f-17-1", info: [""] }),
        new KeymapKey({ name: "0", id: "r-f-21-1", info: [""] }),
        new KeymapKey({ name: "-_", id: "r-f-25-1", info: [""] }),
        new KeymapKey({ name: "FnM", id: "r-f-1-5", info: [""] }),
        new KeymapKey({ name: "y", id: "r-f-5-5", info: [""] }),
        new KeymapKey({ name: "u", id: "r-f-9-5", info: [""] }),
        new KeymapKey({ name: "i", id: "r-f-13-5", info: [""] }),
        new KeymapKey({ name: "o", id: "r-f-17-5", info: [""] }),
        new KeymapKey({ name: "p", id: "r-f-21-5", info: [""] }),
        new KeymapKey({ name: "\\|", id: "r-f-25-5", info: [""] }),
        new KeymapKey({ name: "cmd", id: "r-f-1-9", info: [""] }),
        new KeymapKey({ name: "h", id: "r-f-5-9", info: [""] }),
        new KeymapKey({ name: "j", id: "r-f-9-9", info: [""] }),
        new KeymapKey({ name: "k", id: "r-f-13-9", info: [""] }),
        new KeymapKey({ name: "l", id: "r-f-17-9", info: [""] }),
        new KeymapKey({ name: ";:", id: "r-f-21-9", info: [""] }),
        new KeymapKey({ name: "'\"", id: "r-f-25-9", info: [""] }),
        new KeymapKey({ name: "n", id: "r-f-5-13", info: [""] }),
        new KeymapKey({ name: "m", id: "r-f-9-13", info: [""] }),
        new KeymapKey({ name: ",<", id: "r-f-13-13", info: [""] }),
        new KeymapKey({ name: ".>", id: "r-f-17-13", info: [""] }),
        new KeymapKey({ name: "/?", id: "r-f-21-13", info: [""] }),
        new KeymapKey({ name: "]}", id: "r-f-25-13", info: [""] }),
        new KeymapKey({ name: "opt", id: "r-f-9-17", info: [""] }),
        new KeymapKey({ unset: true, name: "", id: "r-f-13-17", info: [""] }),
        new KeymapKey({ name: "vol-", id: "r-f-17-17", info: [""] }),
        new KeymapKey({ name: "vol+", id: "r-f-21-17", info: [""] }),
        new KeymapKey({ name: "mute", id: "r-f-25-17", info: [""] }),
        // The r-t grid,
        new KeymapKey({ name: "FnB", id: "r-t-1-1", info: [""] }),
        new KeymapKey({ name: "FnA", id: "r-t-5-1", info: [""] }),
        new KeymapKey({ name: "FnC", id: "r-t-1-5", info: [""] }),
        new KeymapKey({ name: "entr", id: "r-t-5-5", info: [""] }),
        new KeymapKey({ name: "spc", id: "r-t-9-5", info: [""] }),
        new KeymapKey({ name: "ctrl", id: "r-t-1-9", info: [""] }),
      ],
    }),
  ],
  guides: [
    new KeymapGuide({
      title: "Layout Guide",
      shortName: "Guide",
      id: "example-guide",
      steps: [
        {
          title: "Welcome to the guide to my main keyboard layout",
          text: [`The first guide step`],
          selection: [],
        },
        { keyId: "l-f-1-1" },
      ],
    }),
  ],
});
